97Fekim/project_green

src/main/java/com/group3/project_green/controller/ListController.java
src/main/java/com/group3/project_green/entity/Post.java
src/main/java/com/group3/project_green/repository/FoodRepository.java
src/main/java/com/group3/project_green/repository/MemberRepository.java
src/main/java/com/group3/project_green/repository/PostRepository.java
src/main/resources/application.properties
src/main/resources/templates/home/list.html
src/test/java/com/group3/project_green/MemberTest.java
src/test/java/com/group3/project_green/PostTests.java

FEAT: ã 더미데이터 추가 및 전체리스트에 불러오기 완료.

---

src/main/java/com/group3/project_green/controller/ListController.java
src/main/java/com/group3/project_green/repository/PostRepository.java
src/main/resources/templates/home/memberPostList.html
src/main/resources/templates/home/readtest.html

memberPostList.html -> bootstrap
readtest.html 만듬
PostRepository 쿼리
Controller -> GetMapping( memberPostList )

PostList bootstrap

---

src/main/java/com/group3/project_green/controller/ListController.java
src/main/java/com/group3/project_green/entity/Post.java
src/main/resources/templates/home/read.html

FEAT:데이터 입력 확인

---

src/main/java/com/group3/project_green/DTO/PostDTO.java
src/main/java/com/group3/project_green/Service/PostService.java
src/main/java/com/group3/project_green/Service/PostServiceImpl.java
src/main/java/com/group3/project_green/controller/ListController.java
src/main/resources/templates/home/list.html

FEAT: PostDTO,Service구현 완료 .

---

src/main/java/com/group3/project_green/DTO/PostDTO.java
src/main/java/com/group3/project_green/Service/PostService.java
src/main/java/com/group3/project_green/Service/PostServiceImpl.java
src/main/java/com/group3/project_green/controller/ListController.java
src/main/java/com/group3/project_green/repository/PostRepository.java
src/main/resources/templates/home/list.html

호상이가 빠트린 부분 수정하고 read 데이터 넘어오는지 확인
repository에서 service로 넘어오게 전부 수정함

FEAT: PostDTO 수정,ListCon /read 부분 수정,Service,Impl 수정,list.html 수정

---

src/main/resources/templates/home/read.html

현재 형님 작업 하실 때  read 페이지에서 바로 이동 가능하도록 수정

FEAT: 현재형님 a tag 넣어드림

---

src/main/java/com/group3/project_green/Service/PostService.java
src/main/java/com/group3/project_green/Service/PostServiceImpl.java
src/main/java/com/group3/project_green/controller/ListController.java
src/main/java/com/group3/project_green/repository/PostRepository.java

넣으면 안돌아가서 일단 주석처리 후 서버 돌아가는거 확인후 넣어둿습니다 .

FEATT: controller , postservice , postServiceImpl, PostRepositor method 추가 진행중 

---

src/main/java/com/group3/project_green/DTO/CommentDTO.java
src/main/java/com/group3/project_green/Service/CommentService.java
src/main/java/com/group3/project_green/Service/CommentServiceImpl.java
src/main/java/com/group3/project_green/controller/CommentController.java
src/main/java/com/group3/project_green/controller/ListController.java
src/main/java/com/group3/project_green/entity/Comment.java
src/main/java/com/group3/project_green/repository/CommentRepository.java
src/main/resources/templates/home/read.html
src/test/java/com/group3/project_green/CommentTests.java

Comment 작업 중...
하다 막혀서 기본 틀만 존재

FEAT: Comment 작업ing

---

src/main/java/com/group3/project_green/DTO/MemberDTO.java

Test MemberDTO

---

src/main/java/com/group3/project_green/Service/MemberService.java
src/main/java/com/group3/project_green/Service/MemberServiceImpl.java
src/main/java/com/group3/project_green/Service/PostService.java
src/main/java/com/group3/project_green/Service/PostServiceImpl.java
src/main/java/com/group3/project_green/controller/ListController.java
src/main/java/com/group3/project_green/repository/PostRepository.java
src/main/resources/templates/home/memberPostList.html

memberPostList_present

---

src/main/java/com/group3/project_green/DTO/PostCommentDTO.java
src/main/java/com/group3/project_green/Service/CommentService.java
src/main/java/com/group3/project_green/Service/CommentServiceImpl.java
src/main/java/com/group3/project_green/Service/PostService.java
src/main/java/com/group3/project_green/Service/PostServiceImpl.java
src/main/java/com/group3/project_green/controller/CommentController.java
src/main/java/com/group3/project_green/controller/ListController.java
src/main/java/com/group3/project_green/repository/CommentRepository.java
src/main/java/com/group3/project_green/repository/PostRepository.java
src/main/resources/templates/home/read.html
src/test/java/com/group3/project_green/CommentTests.java

FEAT:DTO새로 생성 , postRepo getPostByPno 추가 , 댓글 등록 구현

---

src/main/java/com/group3/project_green/controller/CommentController.java
src/main/java/com/group3/project_green/repository/PostRepository.java
src/main/resources/templates/home/read.html

조회 완성, 삭제 진행중(거의 완료) 망할 버튼 안눌림

FEAT: comment 조회 구현, 삭제 진행중

---

src/main/resources/templates/home/list.html

STYLE:list.html 깨짐 수정 , listcontroller 중복 제거 완료

STYLE:list.html 깨짐 수정 , listcontroller 중복 제거 완료

---

src/main/resources/templates/home/read.html

FEAT:댓글 삭제 기능 추가

---

build.gradle
src/main/java/com/group3/project_green/controller/ListController.java
src/main/java/com/group3/project_green/entity/Member.java
src/main/java/com/group3/project_green/entity/MemberInfo.java
src/main/java/com/group3/project_green/memberInfo/UserInfoController.java
src/main/resources/application.properties
src/main/resources/templates/home/insert.html
src/main/resources/templates/home/list.html

FEAT: ãmemberinfo entity 추가 및 개인 담당 페이지 url 매핑

FEAT: ãmemberinfo entity 추가 및 개인 담당 페이지 url 매핑

---

src/main/java/com/group3/project_green/controller/PostListController.java
src/main/resources/templates/home/list.html

FEAT: ㅣ전체리스트,디렉토리별 리스트 비동기식 처리 완료

FEAT: ㅣ전체리스트,디렉토리별 리스트 비동기식 처리 완료

---

src/main/java/com/group3/project_green/DTO/CommentDTO.java
src/main/java/com/group3/project_green/Service/CommentService.java
src/main/java/com/group3/project_green/Service/CommentServiceImpl.java
src/main/java/com/group3/project_green/Session/LoginUser.java
src/main/java/com/group3/project_green/Session/LoginUserArgumentResolver.java
src/main/java/com/group3/project_green/Session/SessionUser.java
src/main/java/com/group3/project_green/Session/WebConfig.java
src/main/java/com/group3/project_green/controller/CommentController.java
src/main/java/com/group3/project_green/controller/ListController.java
src/main/java/com/group3/project_green/entity/Member.java
src/main/resources/templates/home/read.html

FEAT: 댓글 연동,session 부분 추가

---

src/main/java/com/group3/project_green/ProjectGreenApplication.java
src/main/resources/templates/home/list.html

STYLE:List CSS변경 사항 적용중

---

src/main/java/com/group3/project_green/Service/PostService.java
src/main/java/com/group3/project_green/Service/PostServiceImpl.java
src/main/java/com/group3/project_green/controller/ListController.java
src/main/java/com/group3/project_green/repository/PostRepository.java
src/main/resources/templates/home/accomPostList.html
src/main/resources/templates/home/foodPostList.html
src/main/resources/templates/home/sightsPostList.html
src/test/java/com/group3/project_green/PostTests.java

MemberPostList page추가 검색추ì가

---

src/main/java/com/group3/project_green/Service/PostService.java
src/main/java/com/group3/project_green/Service/PostServiceImpl.java
src/main/java/com/group3/project_green/controller/ListController.java
src/main/resources/templates/home/list.html
src/main/resources/templates/home/search.html
src/test/java/com/group3/project_green/PostTests.java

FEAT:homa/list조건검색 구현완료

---

README.md
src/main/resources/templates/home/list.html
src/main/resources/templates/home/search.html

FIX:list 조회시 layout 깨짐 현상 개선 
게시글 검색 조회 시  첫 게시글 이미지 파일이 조회 되는 버그 아직 해결 중 에있습니다 . 
참고바랍니다 .

 FIX:list 조회시 layout 깨짐 현상 개선

---

src/main/resources/templates/home/list.html
src/main/resources/templates/home/search.html

FIX:List img 밀리는 현상 개선

---

src/main/java/com/group3/project_green/DTO/MemberInfoProfileDTO.java
src/main/java/com/group3/project_green/DTO/ProfileImageDTO.java
src/main/java/com/group3/project_green/DTO/ProfileUploadResultDTO.java
src/main/java/com/group3/project_green/Service/MemberinfoService.java
src/main/java/com/group3/project_green/Service/MemberinfoServiceImpl.java
src/main/java/com/group3/project_green/controller/ListController.java
src/main/java/com/group3/project_green/entity/ProfileImage.java
src/main/java/com/group3/project_green/memberInfo/ProfileController.java
src/main/java/com/group3/project_green/memberInfo/UserInfoController.java
src/main/java/com/group3/project_green/repository/MemberinfoRepository.java
src/main/java/com/group3/project_green/repository/ProfileImageRepository.java
src/main/resources/application.properties
src/main/resources/templates/home/accomPostList.html
src/main/resources/templates/home/foodPostList.html
src/main/resources/templates/home/memberPostList.html
src/main/resources/templates/home/sightsPostList.html
src/main/resources/templates/userinfo/userDetail.html
src/main/resources/templates/userinfo/userDetailModify.html

프로필 이미지 등록
